config/routes.rb
Rails.application.routes.draw do

	root 'buildings#index'

	get 'signup', 	to: 'users#new',	 	as: 'signup'
	get 'signin', 	to: 'sessions#new', 	as: 'signin'
	get 'signout',	to: 'sessions#destroy', 	as: 'signout'

	resources :users
	resources :sessions
	resources :buildings do
		resources :reports
	end

	resources :reports

	namespace :api, defaults: { format: 'json'} do
		namespace :v1 do
			resources :buildings
		end
	end

end

app/models/building.rb
class Building < ActiveRecord::Base

	#associations
	has_many :reports

	#validations
	validates :houseno, :streetname, :borough, presence: true

	#callback
	#get building information form the NYC GeoClient API
	after_create :get_building_info

	# methods
	def full_address
		"#{self.houseno}" + " " + "#{self.streetname}"
	end

	def get_building_info

	#require the Ruby classes that let us access URLs from our app
	require 'net/http'
	require 'uri'

	#encode the data we'll feed into the NYC GeoClient API
	houseno		= URI.encode(self.houseno)
    streetname	= URI.encode(self.streetname)
    borough		= URI.encode(self.borough)

    #FILL IN THESE STRINGS WITH YOUR UNIQUE APP_ID & APP_KEY
    app_id = "e32d4e17"
    app_key = "58ad1f19f56264308a28c63b4ec8fa4e"

    #building the URL to request an address from the NYC GeoClient API
    request_url = "https://api.cityofnewyork.us/geoclient/v1/address.json?houseNumber=" + "#{houseno}" + "&street=" + "#{streetname}" + "&borough=" + "#{borough}" + "&app_id=" + "#{app_id}" + "&app_key=" + "#{app_key}"
	#puts "///////////"
	#puts request_url

    #sending a request for the URL
    request = eval(Net::HTTP.get(URI.parse(request_url)))

    #save the info the API returned to our database
    self.bin            = request[:address][:buildingIdentificationNumber]
    self.block          = request[:address][:bblTaxBlock]
    self.lot            = request[:address][:bblTaxLot]
    self.streetname     = request[:address][:boePreferredStreetName]
    self.city           = request[:address][:uspsPreferredCityName]
    self.state          = "NY"
    self.neighborhood   = request[:address][:ntaName]

    self.save!

end
end

app/models/report.rb
class Report < ActiveRecord::Base
	#associations
  belongs_to :building

	#validations
	validates :animal, :number, :datetime, :building_id, presence: true
	validates :number, numericality: true

end

app/models/user.rb
class User < ActiveRecord::Base
	#  gems
	has_secure_password

	#callbacks
	before_create { generate_token(:auth_token ) }

	#methods
	def generate_token(column)
		begin
			self[column] = SecureRandom.urlsafe_base64
		end
	end


end

app/controllers/api/v1/buildings_controller.rb
module Api
	module V1
		class BuildingsController < ApplicationController

			def index
				@buildings = Building.all
			end

		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def current_user
		@current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
	end

	helper_method :current_user

	def authorize
		redirect_to signin_path, alert: "Please log in to continue." if current_user.nil?
	end

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController

	before_action :authorize, except: :index

	def index
		@buildings = Building.all
		@report = Report.new if current_user

		respond_to do |format|
			format.html #index.html.erb
			#format.json #{ render :json => @buildings }
		end
	end
  def new
	  @building = Building.new
  end

  def create
	  @building = Building.new(building_params)

	  if @building.save
		  redirect_to buildings_path, notice: "Building saved!"
	 else
		render 'new', alert: "There was an error"
	end
  end

  def show
	  @building = Building.find(params[:id])
  end

  def edit
	  @building = Building.find(params[:id])
  end

  def update
	@building = Building.find(params[:id])
	if @building.update(building_params)
		redirect_to buildings_path, notice: "Building updated!"
	else
		render 'edit', alert: "There was an error"
	end
  end

  def destroy
	@building = Building.find(params[:id])
	@building.destroy
	redirect_to buildings_path, notice: "Building deleted"
  end



  private
  def building_params
	  params.require(:building).permit(:houseno, :streetname, :borough, :city, :state, :neighborhood, :block, :lot, :bin)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController

  def new
  	@report = Report.new
  end

  def index
    @buildings = Building.all
  end

  def create
  	@report = Report.new(report_params)

  	if @report.save
  		redirect_to root_path
  	else
  		redirect_to root_path, notice: "There was an error!"
  	end
  end

  def show
  end

  def edit
  end

  def destroy
  end

private

	def report_params
		params.require(:report).permit(:animal, :number, :datetime, :building_id)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
	  user = User.find_by_email(params[:email])

		if user && user.authenticate(params[:password])
		  cookies[:auth_token] = user.auth_token
		  redirect_to root_path, notice: "Hi, you've succesfully signed in!"
		else
			flash[:alert] = "Invalid email or password."
			render 'new'
		end
  end

  def destroy
	  cookies.delete(:auth_token)
	  redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :get_user, only: [:show, :edit, :update, :destroy]

  def new
	  redirect_to root_path if current_user
	  @user = User.new
  end

  def create
	  @user = User.new(user_params)

	  if @user.save
		  cookies.permanent[:aut_token] = @user.auth_token
		  redirect_to root_path, notice: "Welcome to Rodent Report!"
	  else
		  render 'new'
	  end
  end

  def show
  end

  def edit
  end

  def update
	  if @user.update(user_params)
		  redirect_to edit_user_path(@user), notice: "Your account has been updated."
	  else
		  render "edit"
	  end
  end

  def destroy
	  @user.destroy
	  redirect_to signout_path, notice: "your account has been deleted."
  end

private

	def user_params
		params.require(:user).permit(:email, :password, :password_confirmation)
	end

	def get_user
		@user = current_user
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
	def animals
		%w{ants bedbugs mice opossums pigeons raccoons rats roaches skunks spiders squirrels termites other unknown}
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buildings/_form.html.erb
<%= simple_form_for @building do |f| %>
	<%= f.input :houseno, label: "House Number" %>
	<%= f.input :streetname, label: "Street Name" %>
	<%= f.input :borough %>
	<%= f.submit %>
<% end %>

app/views/buildings/edit.html.erb
<div class="row">
	<div class="small-12 columns">
		<h1>Edit Building</h1>
		<%= render "form" %>
	</div>
</div>

app/views/buildings/index.html.erb
<div class="row">
	<div class="small-6 columns">
		<h1>Buildings</h1>

		<table>
			<thead>
				<tr>
					<th>Address</th>
					<th>Reports</th>
					<th>Edit</th>
					<th>Delete</th>
				</tr>
			</thead>

			<tbody>
				<% @buildings.each do |building| %>
					<tr>
						<td><%= building.full_address %></td>
						<td><%= building.neighborhood %></td>
						<td><%= link_to building.reports.count, building_path(building) %></td>
						<td><%= link_to "Edit", edit_building_path(building) %></td>
						<td><%= link_to "Delete", building_path(building), method: :delete %></td>
					</tr>
				<% end %>

			</tbody>
		</table>
		<%= link_to "Add Building", new_building_path %>
	</div>
	<div class= "small-6 columns">
         <% if current_user %>
            <h2>Add Report</h2>
			<%= simple_form_for @report do |f| %>
			<%= f.association :building, label_method: :full_address, prompt: "Selecct Building", include_blank: false %>
         	<%= f.input :animal, collection: animals, prompt: "Select" %>
         	<%= f.input :number, collection: 1..10, include_blank: false %>
         	<%= f.input :datetime, as: :string, input_html: {:class=> 'datepicker'} %>
         	<%= f.submit "Report" %>
      		<% end %>
         <% end %>
</div>
</div>

app/views/buildings/new.html.erb
<div class="row">
	<div class="small-12 columns">
		<h1>Add Building</h1>
		<%= render "form" %>
	</div>
</div>

app/views/buildings/show.html.erb
<div class="row">
	<div class="small-12 columns">
		<h3>Building Reports</h3>

		<h1><%= @building.full_address %></h1>

		<table>
			<thead>
				<tr>
					<th>Date</th>
					<th>Animal</th>
					<th>Number</th>
				</tr>
			</thead>
			<tbody>
				<% @building.reports.each do |b| %>
					<tr>
						<td><%= b.datetime.strftime("%D") %></td>
						<td><%= b.animal.capitalize %></td>
						<td><%= b.number %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/layouts/_nav.html.erb
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Rodent Report</li>
	  <li><%= link_to "Buildings", buildings_path %></li>
	  <% if !current_user %>
	  	<li><%= link_to "Sign In", signin_path %></li>
		<li><%= link_to "Sign Up", signup_path %></li>
	  <% else %>
	  	<li><%= link_to "My Profile", edit_user_path(current_user) %></li>
		<li><%= link_to "Sign Out", signout_path %></li>
	  <% end %>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Search"></li>
      <li><button type="button" class="button">Search</button></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rodentreport</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "layouts/nav" %>
<%= yield %>

</body>
</html>

app/views/reports/edit.html.erb
<h1>Reports#edit</h1>
<p>Find me in app/views/reports/edit.html.erb</p>

app/views/reports/new.html.erb
<h1>Reports#new</h1>
<p>Find me in app/views/reports/new.html.erb</p>

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<div class='row'>
	<div class="small-12 columns">
		<h1>Sign up for Rodent Report</h1>
		<%= simple_form_for @user do |f| %>
			<%= f.input :email %>
			<%= f.input :password %>
			<%= f.input :password_confirmation %>
			<%= f.submit "Sign Up" %>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>